[package]
name = "byml_to_yaml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow_ext = "0.2.1"
roead = "0.23.1"
xflags = "0.3.1"
